// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/muhammadheryan/e-commerce/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// GetOrderDetailTx provides a mock function with given fields: ctx, tx, orderID
func (_m *OrderRepository) GetOrderDetailTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) (*model.OrderDetail, error) {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderDetailTx")
	}

	var r0 *model.OrderDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) (*model.OrderDetail, error)); ok {
		return rf(ctx, tx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) *model.OrderDetail); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r1 = rf(ctx, tx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOrderItemsTx provides a mock function with given fields: ctx, tx, orderID, items
func (_m *OrderRepository) InsertOrderItemsTx(ctx context.Context, tx *sqlx.Tx, orderID uint64, items []model.OrderItemRequest) error {
	ret := _m.Called(ctx, tx, orderID, items)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrderItemsTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64, []model.OrderItemRequest) error); ok {
		r0 = rf(ctx, tx, orderID, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertOrderTx provides a mock function with given fields: ctx, tx, req
func (_m *OrderRepository) InsertOrderTx(ctx context.Context, tx *sqlx.Tx, req *model.InsertOrderTxItem) (uint64, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrderTx")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.InsertOrderTxItem) (uint64, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.InsertOrderTxItem) uint64); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *model.InsertOrderTxItem) error); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatusTx provides a mock function with given fields: ctx, tx, orderID, status
func (_m *OrderRepository) UpdateOrderStatusTx(ctx context.Context, tx *sqlx.Tx, orderID uint64, status int) error {
	ret := _m.Called(ctx, tx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatusTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64, int) error); ok {
		r0 = rf(ctx, tx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
