// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/muhammadheryan/e-commerce/model"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// WarehouseRepository is an autogenerated mock type for the WarehouseRepository type
type WarehouseRepository struct {
	mock.Mock
}

// CommitReservationsTx provides a mock function with given fields: ctx, tx, orderID
func (_m *WarehouseRepository) CommitReservationsTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) error {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CommitReservationsTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetReservationsByOrderTx provides a mock function with given fields: ctx, tx, orderID
func (_m *WarehouseRepository) GetReservationsByOrderTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) ([]model.Reservation, error) {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationsByOrderTx")
	}

	var r0 []model.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) ([]model.Reservation, error)); ok {
		return rf(ctx, tx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) []model.Reservation); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r1 = rf(ctx, tx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalAvailableStockTx provides a mock function with given fields: ctx, tx, productID
func (_m *WarehouseRepository) GetTotalAvailableStockTx(ctx context.Context, tx *sqlx.Tx, productID uint64) (int64, error) {
	ret := _m.Called(ctx, tx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAvailableStockTx")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) (int64, error)); ok {
		return rf(ctx, tx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) int64); ok {
		r0 = rf(ctx, tx, productID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r1 = rf(ctx, tx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseReservationsTx provides a mock function with given fields: ctx, tx, orderID
func (_m *WarehouseRepository) ReleaseReservationsTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) error {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseReservationsTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReserveStockTx provides a mock function with given fields: ctx, tx, req
func (_m *WarehouseRepository) ReserveStockTx(ctx context.Context, tx *sqlx.Tx, req *model.ReserveRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStockTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.ReserveRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWarehouseRepository creates a new instance of WarehouseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseRepository {
	mock := &WarehouseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
