// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	constant "github.com/muhammadheryan/e-commerce/constant"

	mock "github.com/stretchr/testify/mock"

	model "github.com/muhammadheryan/e-commerce/model"

	sqlx "github.com/jmoiron/sqlx"
)

// WarehouseRepository is an autogenerated mock type for the WarehouseRepository type
type WarehouseRepository struct {
	mock.Mock
}

// CheckReservedStock provides a mock function with given fields: ctx, warehouseID
func (_m *WarehouseRepository) CheckReservedStock(ctx context.Context, warehouseID uint64) (int64, error) {
	ret := _m.Called(ctx, warehouseID)

	if len(ret) == 0 {
		panic("no return value specified for CheckReservedStock")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (int64, error)); ok {
		return rf(ctx, warehouseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) int64); ok {
		r0 = rf(ctx, warehouseID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, warehouseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitReservationsTx provides a mock function with given fields: ctx, tx, orderID
func (_m *WarehouseRepository) CommitReservationsTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) error {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for CommitReservationsTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetReservationsByOrderTx provides a mock function with given fields: ctx, tx, orderID
func (_m *WarehouseRepository) GetReservationsByOrderTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) ([]model.Reservation, error) {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetReservationsByOrderTx")
	}

	var r0 []model.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) ([]model.Reservation, error)); ok {
		return rf(ctx, tx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) []model.Reservation); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r1 = rf(ctx, tx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalAvailableStockTx provides a mock function with given fields: ctx, tx, productID
func (_m *WarehouseRepository) GetTotalAvailableStockTx(ctx context.Context, tx *sqlx.Tx, productID uint64) (int64, error) {
	ret := _m.Called(ctx, tx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAvailableStockTx")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) (int64, error)); ok {
		return rf(ctx, tx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) int64); ok {
		r0 = rf(ctx, tx, productID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r1 = rf(ctx, tx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWarehouseByID provides a mock function with given fields: ctx, warehouseID
func (_m *WarehouseRepository) GetWarehouseByID(ctx context.Context, warehouseID uint64) (*model.WarehouseEntity, error) {
	ret := _m.Called(ctx, warehouseID)

	if len(ret) == 0 {
		panic("no return value specified for GetWarehouseByID")
	}

	var r0 *model.WarehouseEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*model.WarehouseEntity, error)); ok {
		return rf(ctx, warehouseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *model.WarehouseEntity); ok {
		r0 = rf(ctx, warehouseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WarehouseEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, warehouseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWarehouseStock provides a mock function with given fields: ctx, warehouseID, productID
func (_m *WarehouseRepository) GetWarehouseStock(ctx context.Context, warehouseID uint64, productID uint64) (*model.WarehouseStock, error) {
	ret := _m.Called(ctx, warehouseID, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetWarehouseStock")
	}

	var r0 *model.WarehouseStock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*model.WarehouseStock, error)); ok {
		return rf(ctx, warehouseID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) *model.WarehouseStock); ok {
		r0 = rf(ctx, warehouseID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.WarehouseStock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, warehouseID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseReservationsTx provides a mock function with given fields: ctx, tx, orderID
func (_m *WarehouseRepository) ReleaseReservationsTx(ctx context.Context, tx *sqlx.Tx, orderID uint64) error {
	ret := _m.Called(ctx, tx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseReservationsTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, uint64) error); ok {
		r0 = rf(ctx, tx, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReserveStockTx provides a mock function with given fields: ctx, tx, req
func (_m *WarehouseRepository) ReserveStockTx(ctx context.Context, tx *sqlx.Tx, req *model.ReserveRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStockTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.ReserveRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferStockTx provides a mock function with given fields: ctx, tx, req
func (_m *WarehouseRepository) TransferStockTx(ctx context.Context, tx *sqlx.Tx, req *model.TransferStockRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for TransferStockTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *model.TransferStockRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWarehouseStatus provides a mock function with given fields: ctx, warehouseID, status
func (_m *WarehouseRepository) UpdateWarehouseStatus(ctx context.Context, warehouseID uint64, status constant.WarehouseStatus) error {
	ret := _m.Called(ctx, warehouseID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWarehouseStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, constant.WarehouseStatus) error); ok {
		r0 = rf(ctx, warehouseID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWarehouseRepository creates a new instance of WarehouseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarehouseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WarehouseRepository {
	mock := &WarehouseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
